name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: sprgen-linux
          path: |
            sprgen
            sprinfo

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v5

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            mingw-w64-ucrt-x86_64-gcc
            make

      - name: Build
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: sprgen-windows
          path: |
            sprgen.exe
            sprinfo.exe
